"""add room member receipt settlement settlement_entry file_object tables

Revision ID: e15394e0388c
Revises: 019df012e6f1
Create Date: 2026-09-05 14:11:22.632916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15394e0388c'
down_revision: Union[str, Sequence[str], None] = '019df012e6f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_object',
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('byte_size', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("content_type LIKE 'image/%%'", name='file_object_image_only'),
    sa.CheckConstraint('byte_size > 0', name='file_object_size_pos'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_table('room',
    sa.Column('share_code', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('total_budget', sa.BigInteger(), nullable=False),
    sa.Column('thumbnail_file_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'SETTLED', name='room_status'), server_default='ACTIVE', nullable=False),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'SETTLED' AND settled_at IS NOT NULL) OR (status = 'ACTIVE' AND settled_at IS NULL)", name='room_settled_consistency'),
    sa.CheckConstraint("btrim(title) <> ''", name='room_title_not_blank'),
    sa.CheckConstraint("share_code ~ '^[A-Za-z0-9_-]{8,32}$'", name='room_share_code_fmt'),
    sa.CheckConstraint('char_length(title) <= 50', name='room_title_len'),
    sa.CheckConstraint('total_budget >= 0', name='room_budget_nonneg'),
    sa.ForeignKeyConstraint(['thumbnail_file_id'], ['file_object.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_code')
    )
    op.create_table('member',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_treasurer', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("btrim(name) <> ''", name='member_name_not_blank'),
    sa.CheckConstraint('char_length(name) <= 20', name='member_name_len'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'id', name='member_room_id_uq')
    )
    op.create_index('member_idx_room_order', 'member', ['room_id', 'display_order', 'created_at'], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('member_uq_room_name_alive', 'member', ['room_id', sa.literal_column('lower(btrim(name))')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('member_uq_room_treasurer', 'member', ['room_id'], unique=True, postgresql_where=sa.text('is_treasurer AND deleted_at IS NULL'))
    op.create_table('settlement',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('room_title', sa.Text(), nullable=False),
    sa.Column('budget_amount', sa.BigInteger(), nullable=False),
    sa.Column('period_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_amount', sa.BigInteger(), nullable=False),
    sa.Column('member_count', sa.Integer(), nullable=False),
    sa.Column('per_person_amount', sa.BigInteger(), nullable=False),
    sa.Column('receipt_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('member_count > 0', name='settlement_member_count_pos'),
    sa.CheckConstraint('period_end_at >= period_start_at', name='settlement_period_order'),
    sa.CheckConstraint('receipt_count >= 0', name='settlement_receipts_nonneg'),
    sa.CheckConstraint('total_amount >= 0', name='settlement_total_nonneg'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id')
    )
    op.create_table('receipt',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('payer_member_id', sa.UUID(), nullable=False),
    sa.Column('merchant', sa.Text(), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_file_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("btrim(merchant) <> ''", name='receipt_merchant_not_blank'),
    sa.CheckConstraint('amount > 0', name='receipt_amount_pos'),
    sa.CheckConstraint('char_length(merchant) <= 100', name='receipt_merchant_len'),
    sa.CheckConstraint('description IS NULL OR char_length(description) <= 500', name='receipt_desc_len'),
    sa.ForeignKeyConstraint(['image_file_id'], ['file_object.id'], name='receipt_image_fk', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id', 'payer_member_id'], ['member.room_id', 'member.id'], name='receipt_payer_fk', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], name='receipt_room_fk', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('receipt_idx_room_payer_recent', 'receipt', ['room_id', 'payer_member_id', sa.literal_column('paid_at DESC'), sa.literal_column('id DESC')], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_index('receipt_idx_room_recent', 'receipt', ['room_id', sa.literal_column('paid_at DESC'), sa.literal_column('id DESC')], unique=False, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('settlement_entry',
    sa.Column('settlement_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('member_name', sa.Text(), nullable=False),
    sa.Column('is_treasurer', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('paid_amount', sa.BigInteger(), nullable=False),
    sa.Column('share_amount', sa.BigInteger(), nullable=False),
    sa.Column('balance_amount', sa.BigInteger(), sa.Computed('paid_amount - share_amount', persisted=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('paid_amount >= 0', name='settlement_entry_paid_pos'),
    sa.CheckConstraint('share_amount >= 0', name='settlement_entry_share_pos'),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['settlement_id'], ['settlement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('settlement_id', 'member_id', name='settlement_entry_uq')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settlement_entry')
    op.drop_index('receipt_idx_room_recent', table_name='receipt', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('receipt_idx_room_payer_recent', table_name='receipt', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('receipt')
    op.drop_table('settlement')
    op.drop_index('member_uq_room_treasurer', table_name='member', postgresql_where=sa.text('is_treasurer AND deleted_at IS NULL'))
    op.drop_index('member_uq_room_name_alive', table_name='member', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('member_idx_room_order', table_name='member', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_table('member')
    op.drop_table('room')
    op.drop_table('file_object')
    # ### end Alembic commands ###
